# Generated by Django 4.2.9 on 2024-01-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_graph', models.ImageField(upload_to='%d.%m.%Y', verbose_name='Динамика уровня зарплат по годам(все вакансии и Менеджер IT-проекта')),
                ('second_graph', models.ImageField(upload_to='%d.%m.%Y', verbose_name='Динамика количества вакансий по годам(Менеджер IT-проекта)')),
                ('third_graph', models.ImageField(upload_to='%d.%m.%Y', verbose_name='Динамика количества вакансий по годам(все вакансии)')),
                ('table', models.TextField(blank=True, verbose_name='Таблица')),
            ],
        ),
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_graph', models.ImageField(upload_to='%d.%m.%Y', verbose_name='Уровень зарплат по городам(все вакансии и Менеджер IT-проекта')),
                ('second_graph', models.ImageField(upload_to='%d.%m.%Y', verbose_name='Доля вакансий по городам(Менеджер IT-проекта)')),
                ('third_graph', models.ImageField(upload_to='%d.%m.%Y', verbose_name='Доля вакансий по городам(все вакансии)')),
                ('table', models.TextField(blank=True, verbose_name='Таблица')),
            ],
        ),
        migrations.CreateModel(
            name='LastVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок статистика')),
                ('vacancy', models.CharField(max_length=50, verbose_name='Название вакансии')),
            ],
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='%d.%m.%Y', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, verbose_name='Описание вакансии')),
            ],
        ),
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='%d.%m.%Y', verbose_name='Иконка')),
                ('title', models.CharField(max_length=50, verbose_name='Название вакансии')),
                ('first_link', models.CharField(max_length=50, verbose_name='Первый пункт')),
                ('second_link', models.CharField(max_length=50, verbose_name='Второй пункт')),
                ('third_link', models.CharField(max_length=50, verbose_name='Третий пункт')),
                ('fourth_link', models.CharField(max_length=50, verbose_name='Четвертый пункт')),
                ('fifth_link', models.CharField(max_length=50, verbose_name='Пятый пункт')),
                ('author', models.CharField(max_length=50, verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_graph', models.ImageField(upload_to='%d.%m.%Y', verbose_name='ТОП-20 навыков по годам(Менеджер IT-проекта')),
                ('second_graph', models.ImageField(upload_to='%d.%m.%Y', verbose_name='ТОП-20 навыков по годам(все вакансии)')),
                ('table', models.TextField(blank=True, verbose_name='Таблица')),
            ],
        ),
    ]
