# Generated by Django 4.2.9 on 2024-01-16 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacanciesApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Navigation',
        ),
    ]
