# Generated by Django 4.2.9 on 2024-01-17 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacanciesApp', '0002_delete_navigation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastvacancy',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок статистики'),
        ),
    ]
