# Generated by Django 4.2.9 on 2024-01-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacanciesApp', '0003_alter_lastvacancy_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='first_graph',
            field=models.ImageField(upload_to='%d.%m.%Y', verbose_name='Динамика уровня зарплат по годам(все вакансии и Менеджер IT-проекта)'),
        ),
        migrations.AlterField(
            model_name='geography',
            name='first_graph',
            field=models.ImageField(upload_to='%d.%m.%Y', verbose_name='Уровень зарплат по городам(все вакансии и Менеджер IT-проекта)'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='first_graph',
            field=models.ImageField(upload_to='%d.%m.%Y', verbose_name='ТОП-20 навыков по годам(Менеджер IT-проекта)'),
        ),
    ]
