# Generated by Django 4.2.9 on 2024-01-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacanciesApp', '0004_alter_demand_first_graph_alter_geography_first_graph_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demand',
            name='table',
        ),
        migrations.AddField(
            model_name='demand',
            name='first_table',
            field=models.TextField(blank=True, verbose_name='Таблица-1'),
        ),
        migrations.AddField(
            model_name='demand',
            name='second_table',
            field=models.TextField(blank=True, verbose_name='Таблица-1'),
        ),
        migrations.AddField(
            model_name='demand',
            name='third_table',
            field=models.TextField(blank=True, verbose_name='Таблица-1'),
        ),
    ]
