# Generated by Django 4.2.9 on 2024-01-17 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacanciesApp', '0006_remove_geography_table_remove_skills_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='description',
        ),
        migrations.AddField(
            model_name='main',
            name='first_description',
            field=models.TextField(blank=True, verbose_name='Описание вакансии-1'),
        ),
        migrations.AddField(
            model_name='main',
            name='second_description',
            field=models.TextField(blank=True, verbose_name='Описание вакансии-2'),
        ),
        migrations.AlterField(
            model_name='lastvacancy',
            name='vacancy',
            field=models.TextField(max_length=50, verbose_name='Название вакансии'),
        ),
    ]
