# Generated by Django 4.2.9 on 2024-01-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacanciesApp', '0008_remove_lastvacancy_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='first_graph',
            field=models.ImageField(upload_to='images/%d.%m.%Y', verbose_name='Динамика уровня зарплат по годам(все вакансии и Менеджер IT-проекта)'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='second_graph',
            field=models.ImageField(upload_to='images/%d.%m.%Y', verbose_name='Динамика количества вакансий по годам(Менеджер IT-проекта)'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='third_graph',
            field=models.ImageField(upload_to='images/%d.%m.%Y', verbose_name='Динамика количества вакансий по годам(все вакансии)'),
        ),
        migrations.AlterField(
            model_name='geography',
            name='first_graph',
            field=models.ImageField(upload_to='images/%d.%m.%Y', verbose_name='Уровень зарплат по городам(все вакансии и Менеджер IT-проекта)'),
        ),
        migrations.AlterField(
            model_name='geography',
            name='second_graph',
            field=models.ImageField(upload_to='images/%d.%m.%Y', verbose_name='Доля вакансий по городам(Менеджер IT-проекта)'),
        ),
        migrations.AlterField(
            model_name='geography',
            name='third_graph',
            field=models.ImageField(upload_to='images/%d.%m.%Y', verbose_name='Доля вакансий по городам(все вакансии)'),
        ),
        migrations.AlterField(
            model_name='main',
            name='image',
            field=models.ImageField(upload_to='images/%d.%m.%Y', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='first_graph',
            field=models.ImageField(upload_to='images/%d.%m.%Y', verbose_name='ТОП-20 навыков по годам(Менеджер IT-проекта)'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='second_graph',
            field=models.ImageField(upload_to='images/%d.%m.%Y', verbose_name='ТОП-20 навыков по годам(все вакансии)'),
        ),
    ]
